# Generated by Django 5.2.1 on 2025-06-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book_previouspaper_delete_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='cover_image',
            new_name='image',
        ),
    ]
